name: CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build dependencies
        run: |
          chmod +x ./mvnw
          ./mvnw clean install -DskipTests
      
  build-and-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          chmod +x ./mvnw
          COMMIT_ID="${GITHUB_SHA::7}"
          ./mvnw spring-boot:build-image "-Dspring-boot.build-image.imageName=gildastema/demo-app:${COMMIT_ID}"
          ./mvnw spring-boot:build-image "-Dspring-boot.build-image.imageName=gildastema/demo-app:latest"
        env:
          IMAGE_NAME: gildastema/demo-app
          IMAGE_TAG: ${COMMIT_ID}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Push docker image
        run: |
          COMMIT_ID="${GITHUB_SHA::7}"
          docker push gildastema.azurecr.io/demo-app:${COMMIT_ID}
          docker push gildastema.azurecr.io/demo-app:latest